//! Pure rendering of HTML and JSON error pages with the Incident ID.
use super::trace::trace_hex;
use crate::prelude::{Resp, TraceCtx};
use http::{HeaderMap, HeaderValue, StatusCode, header};
use std::borrow::Cow;
use std::time::SystemTime;

const TEMPLATE: &str = include_str!("fallback.html");
const CSP: &str = "default-src 'none'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Format {
    Html,
    Json,
}

/// JSON if `Accept` asks for JSON and not for HTML, otherwise HTML.
pub fn negotiate(accept: Option<&HeaderValue>) -> Format {
    let a = accept
        .and_then(|v| v.to_str().ok())
        .unwrap_or("")
        .to_ascii_lowercase();
    if (a.contains("application/json") || a.contains("+json")) && !a.contains("text/html") {
        Format::Json
    } else {
        Format::Html
    }
}

pub struct ErrorPage<'a> {
    pub status: StatusCode,
    pub title: &'a str,
    pub message: &'a str,
    pub incident_id: Option<&'a str>,
    pub ts: &'a str,
}

pub fn html_escape(s: &str) -> Cow<'_, str> {
    if !s.contains(['&', '<', '>', '"', '\'']) {
        return Cow::Borrowed(s);
    }
    let mut out = String::with_capacity(s.len() + 8);
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    Cow::Owned(out)
}

fn html_body(p: &ErrorPage<'_>) -> String {
    let block = p.incident_id.map_or_else(String::new, |id| {
        format!(
            "<p class=\"id\">Incident ID: <code id=\"iid\">{}</code> <button type=\"button\" id=\"cp\">Copy</button></p>",
            html_escape(id)
        )
    });
    TEMPLATE
        .replace("{{STATUS}}", p.status.as_str())
        .replace("{{TITLE}}", &html_escape(p.title))
        .replace("{{MESSAGE}}", &html_escape(p.message))
        .replace("{{INCIDENT_BLOCK}}", &block)
        .replace("{{TS}}", &html_escape(p.ts))
}

fn json_body(p: &ErrorPage<'_>) -> String {
    let mut e = serde_json::json!({
        "status": p.status.as_u16(), "title": p.title, "message": p.message, "timestamp": p.ts,
    });
    if let (Some(id), Some(obj)) = (p.incident_id, e.as_object_mut()) {
        obj.insert("incident_id".into(), id.into());
    }
    serde_json::json!({ "error": e }).to_string()
}

pub fn render(p: &ErrorPage<'_>, f: Format) -> Resp {
    let (ctype, body) = match f {
        Format::Html => ("text/html; charset=utf-8", html_body(p)),
        Format::Json => ("application/json", json_body(p)),
    };
    let mut r = crate::prelude::simple(p.status, ctype, body);
    let h = r.headers_mut();
    h.insert(header::CACHE_CONTROL, HeaderValue::from_static("no-store"));
    h.insert("x-content-type-options", HeaderValue::from_static("nosniff"));
    if f == Format::Html {
        h.insert(header::CONTENT_SECURITY_POLICY, HeaderValue::from_static(CSP));
    }
    r
}

/// Default title and message for pages generated by the gateway itself.
pub fn default_texts(status: StatusCode) -> (&'static str, &'static str) {
    match status.as_u16() {
        400 => ("Bad request", "The request could not be understood."),
        401 => (
            "Authentication required",
            "You must authenticate to access this resource.",
        ),
        403 => ("Access denied", "You are not allowed to access this resource."),
        404 => ("Unknown site", "No site is configured for this domain name."),
        413 => ("Request too large", "The request body exceeds the allowed size."),
        429 => ("Too many requests", "Please wait before trying again."),
        508 => (
            "Loop detected",
            "The request was rejected because it loops through the gateway.",
        ),
        _ => ("Error", "An error occurred."),
    }
}

pub fn now_rfc3339() -> String {
    humantime::format_rfc3339_millis(SystemTime::now()).to_string()
}

pub fn render_error(status: StatusCode, req_headers: &HeaderMap, trace: &TraceCtx) -> Resp {
    let (title, message) = default_texts(status);
    let id = trace_hex(trace.trace_id);
    let ts = now_rfc3339();
    let page = ErrorPage {
        status,
        title,
        message,
        incident_id: Some(&id),
        ts: &ts,
    };
    render(&page, negotiate(req_headers.get(header::ACCEPT)))
}

#[cfg(test)]
mod tests {
    use super::*;
    use http_body_util::BodyExt;

    fn page(id: Option<&str>) -> ErrorPage<'_> {
        ErrorPage {
            status: StatusCode::SERVICE_UNAVAILABLE,
            title: "T<b>",
            message: "M&\"'",
            incident_id: id,
            ts: "now",
        }
    }

    async fn text(r: Resp) -> String {
        String::from_utf8(r.into_body().collect().await.unwrap().to_bytes().to_vec()).unwrap()
    }

    #[test]
    fn negotiate_json_vs_html() {
        let h = |s: &'static str| HeaderValue::from_static(s);
        assert_eq!(negotiate(None), Format::Html);
        assert_eq!(negotiate(Some(&h("application/json"))), Format::Json);
        assert_eq!(negotiate(Some(&h("application/problem+json"))), Format::Json);
        assert_eq!(negotiate(Some(&h("text/html,application/json"))), Format::Html);
        assert_eq!(negotiate(Some(&h("*/*"))), Format::Html);
    }

    #[tokio::test]
    async fn html_escapes_all() {
        let body = text(render(&page(Some("a<b")), Format::Html)).await;
        assert!(body.contains("T&lt;b&gt;") && body.contains("M&amp;&quot;&#39;") && body.contains("a&lt;b"));
        assert!(!body.contains("T<b>"));
    }

    #[tokio::test]
    async fn html_has_incident_id_and_csp() {
        let r = render(&page(Some("abc123")), Format::Html);
        assert!(r.headers().contains_key(header::CONTENT_SECURITY_POLICY));
        assert_eq!(r.headers()[header::CACHE_CONTROL], "no-store");
        assert!(text(r).await.contains("<code id=\"iid\">abc123</code>"));
    }

    #[tokio::test]
    async fn json_omits_incident_when_disabled() {
        let v: serde_json::Value =
            serde_json::from_str(&text(render(&page(None), Format::Json)).await).unwrap();
        assert_eq!(v["error"]["status"], 503);
        assert!(v["error"].get("incident_id").is_none());
        let v: serde_json::Value =
            serde_json::from_str(&text(render(&page(Some("x")), Format::Json)).await).unwrap();
        assert_eq!(v["error"]["incident_id"], "x");
    }

    #[test]
    fn html_template_is_small() {
        assert!(TEMPLATE.len() < 4096);
    }

    #[tokio::test]
    async fn render_error_uses_trace_id() {
        let t = TraceCtx {
            trace_id: 0xabc,
            parent_span: None,
            span_id: 1,
            sampled: true,
        };
        let mut h = HeaderMap::new();
        h.insert(header::ACCEPT, HeaderValue::from_static("application/json"));
        let r = render_error(StatusCode::NOT_FOUND, &h, &t);
        assert_eq!(r.status(), 404);
        assert!(text(r).await.contains("00000000000000000000000000000abc"));
    }
}
